name: Loisnicholls
favicon: null
layout_spectrum: 0.3128925831988454
typography_spectrum: 0.99801
title: 'Columns, articles and musings'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4feff'
    - '#000105'
    - '#aa9f7f'
    - '#66190f'
    - '#3d4d28'
  brandStrength: 0.5
  lightness: 0.4374968260526657
  saturation: 0.2493540628347546
  rhythmicContrast: 0.3825627863407135
purpose: []
