name: Loisnicholls
favicon: null
layout_spectrum: 0.3128925831988454
typography_spectrum: 0.99801
title: 'Columns, articles and musings'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#9d9cac'
    - '#816d64'
    - '#ddedfa'
    - '#473728'
  brandStrength: 0
  lightness: 0.4374968260526657
  saturation: 0.2493540628347546
  rhythmicContrast: 0.3825627863407135
purpose: []
